name: Python Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.11']  # Reduced matrix for faster feedback

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pandas openpyxl xlrd
    
    - name: Install package in development mode
      run: |
        pip install -e .
    
    - name: Verify package installation
      run: |
        python -c "
        try:
            import excel_dumper
            print('✅ excel_dumper package imported successfully')
            from excel_dumper.dumper import extract_excel_data, has_non_null_data
            print('✅ Main functions imported successfully')
            
            # Test basic functionality
            result = has_non_null_data(['test'])
            assert result == True
            print('✅ Basic functionality verified')
        except Exception as e:
            print(f'❌ Package verification failed: {e}')
            exit(1)
        "
    
    - name: List test files
      shell: bash
      run: |
        echo "Looking for test files..."
        find . -name "test_*.py" -type f | head -10 || true
        echo "Python files in current directory:"
        find . -name "*.py" -type f | grep -E "(test_|conftest)" | head -10 || true
    
    - name: Run pytest discovery
      run: |
        echo "Testing pytest discovery..."
        python -m pytest --collect-only -q || echo "Pytest collection failed"
    
    - name: Run tests from tests directory
      if: hashFiles('tests/test_*.py') != ''
      run: |
        echo "Running tests from tests/ directory"
        python -m pytest tests/ -v --tb=short --maxfail=3
    
    - name: Run tests from root directory
      if: hashFiles('test_*.py') != ''
      run: |
        echo "Running tests from root directory"
        python -m pytest . -k "test_" -v --tb=short --maxfail=3
    
    - name: Run specific test files (fallback)
      shell: bash
      run: |
        echo "Attempting to run individual test files..."
        for test_file in $(find . -name "test_*.py" -type f | head -5); do
          echo "Running $test_file"
          python -m pytest "$test_file" -v --tb=short --maxfail=1 || echo "Failed: $test_file"
        done

  quick-test:
    # Simplified job that just runs one test file to verify basics
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install pytest pandas openpyxl xlrd
        pip install -e .
    
    - name: Find and run one test
      run: |
        # Find any test file and try to run it
        test_file=$(find . -name "test_*.py" -type f | head -1)
        if [ -n "$test_file" ]; then
          echo "Found test file: $test_file"
          echo "Attempting to run: $test_file"
          python -m pytest "$test_file" -v -x
        else
          echo "No test files found"
          exit 1
        fi
